import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useCallback } from 'react';
import { useQuery } from "react-query";

import { UserService } from "../src/services";
import { AuthService,SignupParams } from "../src/services";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const handleSignup = useCallback(() => {
      AuthService.signup({
        email: "hong@gmail.com", 
        password: "111", 
        name:"hong",
        phoneNumber:"342", 
        agreements: {
          privacy: false,
          ad: false,
        }})
    },[])
  
    const handleLogin = useCallback(() => {
      AuthService.login({
        email: "hong@gmail.com", 
        password: "111"})
    },[])
  

  const { data: refreshData } = useQuery("refresh", AuthService.refresh,{
    retry:false
  });
  // const { data: readData } = useQuery("me", ()=>UserService.read(10));
  // const { status: signupStatus } = useQuery("signup", handleSignup);
  // const { data: loginData ,status: loginStatus } = useQuery("login", handleLogin);

  console.log("refreshData", refreshData);
  // console.log("login", loginData,loginStatus );
  // console.log("meData", meData );
  // console.log("readData", readData );

  return (
    <div className={styles.container}>
      <Head>
        <title>NUMBLE:: 쿠팡 클론</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hello World!</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>src/services</code>,
          <code className={styles.code}>src/hooks</code>
        </p>
        <a href="/signup">Go To Sign up page!</a>
        <a href="/login">Go To Login page!</a>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/numble.png" alt="NUMBLE Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
